# PostgreSQL version
#   gem install pg
development:
  adapter: postgresql
  encoding: unicode
  database: eventshare_development
  pool: 5
  username: admin 
  password: baconstripkittenrainbow 
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: eventshare_production
  pool: 5
  username: admin 
  password: baconstripkittenrainbow 
  host: localhost
